<?php
require(get_parent_theme_file_path('/functions/util.php'));
require(get_parent_theme_file_path('/functions/setup.php'));
require(get_parent_theme_file_path('/functions/general.php'));
require(get_parent_theme_file_path('/functions/widget.php'));
require(get_parent_theme_file_path('/functions/nav.php'));
require(get_parent_theme_file_path('/functions/meta.php'));
require(get_parent_theme_file_path('/functions/short-code.php'));
require(get_parent_theme_file_path('/functions/editor.php'));
require(get_parent_theme_file_path('/functions/customizer.php'));
if(is_actived_plugin('wp-unit')===true){
    require(get_parent_theme_file_path('/inc/unit-test.php'));
}